name: CI

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

jobs:
  lint-changed:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.2

      - name: Setup NodeJs
        uses: actions/setup-node@v6.3.0
        with:
          node-version: 22

      - name: Install dependencies
        run: npm ci

      - name: Run lint
        run: npm run lint

      - name: Run format test
        run: npm run format:check

      - name: Run functionality check
        run: npm run test
